import { Incident, IncidentSeverity, IncidentStatus } from "@/types/incident";

// Dummy monitor data for incidents
const dummyMonitors = [
  { id: "monitor-1", name: "google.com", url: "https://google.com" },
  {
    id: "monitor-2",
    name: "sabcube.vercel.app",
    url: "https://sabcube.vercel.app",
  },
  { id: "monitor-3", name: "api.example.com", url: "https://api.example.com" },
  { id: "monitor-4", name: "dashboard.app", url: "https://dashboard.app" },
  {
    id: "monitor-5",
    name: "removed monitor",
    url: "https://removed-monitor.com",
  },
];

// Dummy comments data
const dummyComments = [
  {
    id: "comment-1",
    description: "Investigating the issue",
    incidentId: "incident-1",
    userId: "user-1",
    createdAt: new Date("2024-07-16T10:17:00Z"),
    user: { id: "user-1" },
  },
  {
    id: "comment-2",
    description: "Issue has been identified and we are working on a fix",
    incidentId: "incident-2",
    userId: "user-1",
    createdAt: new Date("2024-07-14T09:00:00Z"),
    user: { id: "user-1" },
  },
];

export function generateDummyIncidents(): Incident[] {
  const incidents: Incident[] = [
    {
      id: "incident-1",
      title: "Manually reported: jkasHDJSh",
      description: "JkasHDJSh",
      severity: "MINOR" as IncidentSeverity,
      status: "ACKNOWLEDGED" as IncidentStatus,
      monitorId: "monitor-1",
      createdAt: new Date("2024-07-16T10:17:00Z"),
      updatedAt: new Date("2024-07-16T10:17:00Z"),
      escalated: false,
      Monitor: dummyMonitors[0],
      comments: [dummyComments[0]],
    },
    {
      id: "incident-2",
      title: "google.com",
      description: "Sample incident",
      severity: "MAJOR" as IncidentSeverity,
      status: "ONGOING" as IncidentStatus,
      monitorId: "monitor-1",
      createdAt: new Date("2024-07-14T09:00:00Z"),
      updatedAt: new Date("2024-07-14T09:00:00Z"),
      escalated: true,
      Monitor: dummyMonitors[0],
      comments: [dummyComments[1]],
    },
    {
      id: "incident-3",
      title: "sabcube.vercel.app",
      description: "Status 403",
      severity: "MINOR" as IncidentSeverity,
      status: "RESOLVED" as IncidentStatus,
      monitorId: "monitor-2",
      createdAt: new Date("2024-07-23T15:30:00Z"),
      updatedAt: new Date("2024-07-23T15:33:00Z"),
      resolvedAt: new Date("2024-07-23T15:33:00Z"),
      downtime: 3,
      escalated: false,
      Monitor: dummyMonitors[1],
      comments: [],
    },
    {
      id: "incident-4",
      title: "removed monitor",
      description: "SSL peer certificate or SSH remote key was not OK",
      severity: "CRITICAL" as IncidentSeverity,
      status: "RESOLVED" as IncidentStatus,
      monitorId: "monitor-5",
      createdAt: new Date("2024-07-24T11:16:00Z"),
      updatedAt: new Date("2024-07-24T11:18:00Z"),
      resolvedAt: new Date("2024-07-24T11:18:00Z"),
      downtime: 2,
      escalated: false,
      Monitor: dummyMonitors[4],
      comments: [],
    },
    {
      id: "incident-5",
      title: "removed monitor",
      description: "SSL peer certificate or SSH remote key was not OK",
      severity: "CRITICAL" as IncidentSeverity,
      status: "RESOLVED" as IncidentStatus,
      monitorId: "monitor-5",
      createdAt: new Date("2024-07-24T11:10:00Z"),
      updatedAt: new Date("2024-07-24T11:12:00Z"),
      resolvedAt: new Date("2024-07-24T11:12:00Z"),
      downtime: 2,
      escalated: false,
      Monitor: dummyMonitors[4],
      comments: [],
    },
    {
      id: "incident-6",
      title: "api.example.com",
      description: "High latency detected",
      severity: "MAJOR" as IncidentSeverity,
      status: "ONGOING" as IncidentStatus,
      monitorId: "monitor-3",
      createdAt: new Date("2024-07-24T14:20:00Z"),
      updatedAt: new Date("2024-07-24T14:20:00Z"),
      escalated: true,
      Monitor: dummyMonitors[2],
      comments: [],
    },
    {
      id: "incident-7",
      title: "dashboard.app",
      description: "Service degradation",
      severity: "MINOR" as IncidentSeverity,
      status: "ACKNOWLEDGED" as IncidentStatus,
      monitorId: "monitor-4",
      createdAt: new Date("2024-07-24T16:45:00Z"),
      updatedAt: new Date("2024-07-24T16:45:00Z"),
      escalated: false,
      Monitor: dummyMonitors[3],
      comments: [],
    },
  ];

  return incidents;
}
